### ISSUE TITLE
Setup clang-format

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#191]

**Comment by s-martin** [comment]
I would be interested in helping out with this or other issues. 
Could you detail a little bit, what formatting you would expect, if some help is wanted?

There are some other issues I probably could help out (e.g. enums refactor), but some details would be needed.

**Comment by lethal-guitar** [comment]
@s-martin awesome, help is very welcome! For formatting, I would imagine a two-step approach:

1. Write the `.clang-format` config file, and reformat all the code in one big commit
2. Set up something on CI to reject PRs that don't have clang-formatted code, to make sure any future changes are also formatted properly going forward.

As for formatting itself, I would hope we can find a style that's relatively close to the current (manual) formatting. Although I don't believe clang-format supports my somewhat unusual way of positioning the opening brace (`{`), so I would lean towards putting it on the next line instead, as I think the vertical separation between e.g. function header and body is quite important for readability.

Let me know, is this enough information to get started?

I'll add detail to the enum-related issue now as well.
