### ISSUE TITLE
Replace boost::program_options

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#192]
~~https://github.com/philsquared/Clara could be an option once it gets more stable.~~ Not maintained anymore.

I looked into https://github.com/jarro2783/cxxopts as well, but wasn't happy about compile times.

**Comment by viki-t-s** [comment]
Clara is not maintained anymore. But just saw in that github about an actively maintained [fork called Lyra](https://github.com/bfgroup/Lyra). Last commit was 8 days ago.

**Comment by lethal-guitar** [comment]
Thanks for the pointer, I just had a quick look and that seems pretty promising! 👍🏻
