### ISSUE TITLE
Combine sprite textures into texture atlas

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#240]
Currently, one OpenGL texture is created for each animation frame in a sprite. It would be better to combine all sprites into one texture atlas. This could even be done at startup time, further reducing the level load time. This won't make any noticeable difference on Desktops, but on the Raspberry Pi, this could potentially improve rendering performance.

[stb_rect_pack](https://github.com/nothings/stb/blob/master/stb_rect_pack.h) seems like a good library to use.

**Comment by pratikone** [comment]
Oh wow. Didn't know it could cause performance issues. Happy to see this in. I would say another blog post worthy topic

**Comment by lethal-guitar** [comment]
@pratikone most computers are much too powerful for this to make any difference, but on a Raspberry Pi, it does actually help.

The whole topic of optimizing for the Raspberry Pi  would be interesting for a blog post (or series of posts), I think. But at the moment, I prefer to use the time I can dedicate to the project for development rather than writing, so I don't think I'll get to that anytime soon.
