### ISSUE TITLE
win binary pls

### ISSUE THREAD

**Issue by necros2k7** [lethal-guitar/RigelEngine#257]
subj

**Comment by lethal-guitar** [comment]
Hi @necros2k7 

Sorry for not responding until now, I didn't work on the project for a while, and didn't even check my GitHub notifications.

I've just made a release where you can download a binary: https://github.com/lethal-guitar/RigelEngine/releases/tag/v0.0.1

Note that you might have to install the *Visual Studio Redistributable*, there's more info and a download link on the release description.

Have fun with RigelEngine, and let me know if there are any problems!

I'm also curious how you discovered the project, if you don't mind me asking! :)

**Comment by necros2k7** [comment]
Thanx for release! I discovered it by googling "github Duke Nukem" if I`m not mistaken.
