### ISSUE TITLE
Daily build using Travis/Appveyor?

### ISSUE THREAD

**Issue by necros2k7** [lethal-guitar/RigelEngine#325]
subj

**Comment by lethal-guitar** [comment]
AppVeyor is already creating a zip file for each build. You can get there by going to [the project's AppVeyor page](https://ci.appveyor.com/project/lethal-guitar/rigelengine/branch/master), clicking on `Configuration: Release` and then clicking on `Artifacts`. [Here](https://ci.appveyor.com/api/buildjobs/ul7yqnt8h5iw0e3s/artifacts/rigel_build.zip) is the latest build as of now.

**Comment by lethal-guitar** [comment]
Let me see if I can add something to the README to make this easier to find, thanks for the suggestion!
