### ISSUE TITLE
Black screen, music in background (win10 x64), anyone else?

### ISSUE THREAD

**Issue by necros2k7** [lethal-guitar/RigelEngine#326]
subj

**Comment by necros2k7** [comment]
Apogee title then black screen...

**Comment by lethal-guitar** [comment]
@necros2k7 thanks for reporting, and sorry I didn't see this until now! Can you give some more details about your system, i.e. what graphics card and driver version etc.? I have not tried running it on Windows 10 recently, it's possible that there's some issue.

**Comment by lethal-guitar** [comment]
@necros2k7 I've just published [a new release](https://github.com/lethal-guitar/RigelEngine/releases/tag/v0.2.1-alpha), which fixes the issue for me. Let me know if this also solves it for you!

**Comment by necros2k7** [comment]
fixed
