### ISSUE TITLE
Wrong dependencies, when starting from Windows (using vcpkg)

### ISSUE THREAD

**Issue by s-martin** [lethal-guitar/RigelEngine#370]
I'm using `vcpkg` for dependencies under Windows (description see #369).

However, I now have a strange behavior, when I try to start it from VS.

If I run a Debug configuration, `SDL2.dll` is required, but when I run the Release configuration `SDL2d.dll` is required, which is pretty mixed up.

vcpkg ensures that `SDL2d.dll` is in the Debug bin folder and `SDL2.dll` in the Release bin folder. 
All files are actually there, but somehow the Debug program is looking for the Release DLL and the Release program for the Debug dll.

**Comment by lethal-guitar** [comment]
That's very strange indeed 🤔 Maybe an issue with the `FindSDL2.cmake` I'm using. I'll look into it later today

**Comment by s-martin** [comment]
For the tests, the Debug dir doesn't contain any DLL, the Release dir contains the `SDL2.dll` and tests runs fine without any errors (i.e. requires the correct DLL).
