### ISSUE TITLE
Building on raspberry pi

### ISSUE THREAD

**Issue by HereticOne** [lethal-guitar/RigelEngine#381]
Been trying to get this to compile for the raspberry pi

pi@CyPi:~/RigelEngine/build $ cmake .. -DWARNINGS_AS_ERRORS=OFF
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
CMake 3.12 or higher is required.  You are running version 3.7.2

and

CMake Error at /usr/share/cmake-3.7/Modules/FindBoost.cmake:1831 (message):
Unable to find the requested Boost libraries.
Boost version: 1.62.0
Boost include path: /usr/include
Detected version of Boost is too old.

Sadly these are the most up to date libs and compilers.

**Comment by lethal-guitar** [comment]
Thanks for reporting! I would recommend cross-compilation when building for the Raspberry Pi: Building ARM binaries on your Desktop/Laptop and then copying them over to the PI. This way, you can use newer versions of the tools and libraries, independent of what's supported on the Pi. Plus, compiling will be _much_ faster. I haven't tried this myself, but it seems you can use Docker for this nowadays: https://desertbot.io/blog/how-to-cross-compile-for-raspberry-pi

Maybe worth a shot?

CMake 3.8 is the first version that introduced C++ 17 support, so anything lower than that would require changes to the code to work, and/or changes to the CMake files. Boost 1.62 might be less of a problem, but I'd have to check.

Sorry that I can't offer much more help at the moment - I'd like to give some love to the RPI version in general (the shaders need some optimization work to run well on the 1st gen RPI, for example), and having build instructions would be great as well - but don't know when I'll get around to it.

**Comment by Exarkuniv** [comment]
just wanted to let you know i was able to compile it on my Pi3 with out a problem. 
i cant run it though. i get `ERROR: SDL error: Could not create GLES window surface`

im sure its due to me running RetroPie. and there is no desktop. 
but im not too sure. im very new with compiling stuff. 

i did know it was a long shot when i started to compile it. lol

**Comment by lethal-guitar** [comment]
@Exarkuniv thanks for letting me know, good to know that it builds without problems these days! Too bad it doesn't run out of the box yet..

It's generally possible on the Raspberry Pi to run OpenGL applications without a desktop environment (i.e. X server), but I remember having to build SDL with specific configuration flags to enable the corresponding driver. This was ages ago though, so I don't remember any specifics unfortunately, and I don't know how the situation is nowadays. I found [this discussion](https://discourse.libsdl.org/t/problems-using-sdl2-on-raspberry-pi-without-x11-running/22621) after a quick search, maybe something in there helps?

How did you install SDL?

**Comment by Exarkuniv** [comment]
i belive that SDL is part of the image from RetroPie. just not sure on the version

and one of the other guys at the RetroPie forums also mentioned to use `startx` to start it. 
im going to give that a shot once i have a little time. 
and ill also look at that you linked too. 

ill get back to you on it. 

from what i have seen Great work on putting this together. im really hoping i can get this to work.

**Comment by pratikone** [comment]
I believe it is safe to assume wherever glxgears works, RigelEngine will work. Can the pi launch it ?

**Comment by lethal-guitar** [comment]
It should run, but I haven't tested it in a long time, so there might be issues. Back when I implemented the OpenGL renderer, I did some tests on a 1st generation Pi to make sure the GL ES version works, and it ran quite well. But that was in 2017, and I haven't gotten around yet to working with a Pi again.

My ultimate goal is to setup a solid cross compilation process on CI, and then we could bundle ready to use Raspberry Pi binaries with each release.

In the meantime, if we can get things to work for @Exarkuniv, that would already be a great step. And we could add some info to the README on how to build for the Pi then, which would be nice.

**Comment by lethal-guitar** [comment]
Hi @Exarkuniv, how are things going, any luck in getting it to run on the Pi?

**Comment by lethal-guitar** [comment]
@Exarkuniv ok, I've managed to get my own Pi back up and running, and do some testing. I found some problems which currently prevent it from working. I'm still working on fixing everything, I'll let you know when I have an update.

**Comment by Exarkuniv** [comment]
@lethal-guitar. 
i have not done much with it. as i came across a problem. there are two builds im playing around with. 
one is using Buster. and that one was able to get your engine to build perfect. but a few other games that i was working on would not build. 
So i went back to a older version that was on Stretch and your engine would not build but the other one i was working on did.  they are both on the Pi3b, and i might be getting a Pi4 soon so i decided to put a pin in this and wait till i got the Pi4. 

But here is the error i was getting on my Pi3 with Stretch 
``Could NOT find Boost: Found unsuitable version "1.62.0", but required is at
  least "1.65" (found /usr/include)
``
im still a little new with all of this but i did not find a way to get the right version on my build.
so for now it got moved to the back burner

**Comment by lethal-guitar** [comment]
@Exarkuniv yeah, unfortunately Buster is the only version at the moment which has recent enough packages for Boost, CMake and Gcc. 

I got some news: I spent a bit more time getting it to work on my Pi 3, and I now have a working version when using the branch from #547! For it to work, you need to pass `-DUSE_GL_ES` to CMake before building. I then ran it outside of the Desktop environment (by switching to a new terminal using Ctrl+Alt+F1), and it runs ok, but there are some issues:

* No mouse input detected, so the options menu is not usable. I had to run it from within X once to be able to configure the game path.
* Performance is not great, in-game, I only get about 18 to 20 FPS.
* The water effect has some visual artifacts

When running inside of X, performance is abysmal, with only 5 FPS even in the menus. So running outside of X is really the only way to get playable performance.

I'll add some information to the README, create follow-up issues, and then close this one.
