### ISSUE TITLE
Make camera configurable

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#384]
Make it possible to configure the camera dead zones. There would be a couple of options:

* Original - original camera without changes 
* Centered - always keep Duke in the center of the screen, so the camera scrolls sooner
* Edges - always keep Duke at the opposite edge of the screen. If he is moving to the right, keep him at the left edge of the screen, when moving to the left, keep him at the right edge.

**Comment by DuoDynamo** [comment]
I really hope this gets added soon. It always felt weird and counter-intuitive to have Duke closer to the screen edge he's facing/walking towards as opposed to farther. It limits visibility for no good reason. Widescreen does help a lot, but it's still a pet peeve of mine.

I'm assuming this was present in the vanilla game to reduce the draw distance for performance reasons, but I doubt that'd be an issue now.

**Comment by lethal-guitar** [comment]
Hi @DuoDynamo, thanks for your message! This is definitely one of the more frequently requested enhancements. I haven't prioritized it so far since - as you mention - widescreen mode already improves the situation quite a bit. But I'm happy to look into it soon.
