### ISSUE TITLE
Pull up-scaling logic out of `Renderer`

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#387]
The original Duke Nukem II uses a 320x200 resolution, which on CRTs of the time was stretched vertically to produce a 4:3 aspect ratio image. To keep things simple, RigelEngine currently renders everything into a 320x200 render target, and then scales that up to full screen resolution. This makes things very straightforward, because all the code can be written as if we were still drawing to a screen of that resolution. But this simplicity also means there is not a lot of flexibility. 

Going forward, we'll want to be able to render at full resolution to implement various enhancements. This means up-scaling at the top level needs to be replaced with a system where we can easily switch between full-screen rendering and automatic up-scaling.

There a couple of changes involved in this:

* Make the top-level render target in `game_main.cpp` as big as the full screen resolution, instead of 320x200 (this means we need to pass the window size into `Game` as ctor arguments). Note that we have to keep the top-level render target for fade-in/fade-out effects, even if we're not using it for up-scaling.
* Write a utility function that sets up the global scale, global translation, and clip rect settings of `Renderer` in a way that results in the same up-scaling currently achieved with the 320x200 render target
* Use this utility function to set up up-scaling by default (game modes can override it by changing the scale/translation/clip rect settings accordingly).

**Comment by lethal-guitar** [comment]
@pratikone I started doing this today, but didn't quite finish yet - I have some work in progress state on [a branch](https://github.com/lethal-guitar/RigelEngine/commit/1c9a77bf41587c24ee3efa4a75f68abd674dab3f), but the scale factor calculation isn't quite correct yet, and the code in `GameWorld::render` needs adaptation. Not much left though, and I might be able to finish it tomorrow. Just thought I'd give you a heads-up, as this should make your life much easier for the wide screen support!

**Comment by pratikone** [comment]
Thank you for this change and helping me out with the issues. I will use these changes in my code. On a side note, I think you have done some really cool things in the engine, architecture wise as well as good examples of C++ new features. If you start writing blog posts on different parts of the engine development, it will be a really cool way to let people know the tech behind the engine as well as popularising this project, in general.

**Comment by lethal-guitar** [comment]
Thanks for the kind words! Yeah, I'd love to write more about the project - there's lots to talk about for sure :grin:
