### ISSUE TITLE
Allow non-archived data files to be read by engine

### ISSUE THREAD

**Issue by ZeroDiamond** [lethal-guitar/RigelEngine#396]
The original NUKEM2.EXE will, given loose files in the directory matching the names of the ones stored in its archives, load those instead of the internal files.  This can be confirmed by use of the modified .MNI files I've attached, which can then be placed in a DOS Duke Nukem 2 install and will replace the "I'm BACK" samples in-game as well as Duke's pain and death sounds.  Do note however that the original EXE has the size of each sound hard coded and, in my experience, it will crash when attempting to end E1L2.  Supporting this without that limitation would not only improve accuracy but also allow for modders to have more flexibility.

EDIT: Apparently despite saying it supports ZIP, GitHub won't let me upload it directly to this, so here's a link: https://www.mediafire.com/file/gtdri8rx8n249yr/MNI_TEST.zip/file

**Comment by lethal-guitar** [comment]
Hi @ZeroDiamond, thanks for reporting! This is something I definitely want to do, I also made an issue about it ages ago: https://github.com/lethal-guitar/RigelEngine/issues/190.

I'll see if I can get this done sometime soon.

**Comment by lethal-guitar** [comment]
@ZeroDiamond FYI, there's now a build available which implements this: https://ci.appveyor.com/api/buildjobs/ydvtp2x60b6moolg/artifacts/rigel_build.zip

I was able to successfully use the files from your Zip file. I also tried the [sunglasses patch](https://forums.duke4.net/topic/8736-sunglass-patch-for-duke-nukem-2/), and that worked as well.

Let me know if you encounter any issues.
