### ISSUE TITLE
Newest build requires libmpg123.dll, not included

### ISSUE THREAD

**Issue by ZeroDiamond** [lethal-guitar/RigelEngine#400]
Pretty much what the title says.  I've tried a few different versions available on the web, but all of them just cause it to immediately crash with "The application was unable to start correctly."  Asked around and was told I should probably open an issue regarding this.

**Comment by pratikone** [comment]
It should not.  I am using the latest version and it doesn't require libmpg123.dll and it doesn't use the library in the code anywhere. Can you provide some details about your system like OS, compiler, SDL, Boost versions etc

**Comment by ZeroDiamond** [comment]
I am on Windows 7 and I didn't build it myself at all, I just downloaded the pre-built version available here: https://github.com/lethal-guitar/RigelEngine/releases/download/v0.4.2-beta/rigel_build.zip

**Comment by ZeroDiamond** [comment]
I am on Windows 7 and I didn't build it myself at all, I just downloaded the pre-built version available here: https://github.com/lethal-guitar/RigelEngine/releases/download/v0.4.2-beta/rigel_build.zip

**Comment by lethal-guitar** [comment]
@ZeroDiamond thanks for reporting, and sorry about that! I've re-uploaded the build with a corrected version of `SDL2_mixer.dll`, that doesn't need these other DLLs. Can you re-download the build and let me know if it works for you know?

**Comment by lethal-guitar** [comment]
@ZeroDiamond I'm assuming the issue is fixed for you now. Feel free to reopen if there are still problems.
