### ISSUE TITLE
Options menu: Implement a "frame rate limit" option

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#407]
When disabling v-sync, the game runs extremely fast on modern hardware (it reaches several thousand FPS on my machine). This isn't really desirable, so it would be nice if there was an optional FPS cap/framerate limiter which could be used instead of v-sync.

**Comment by pratikone** [comment]
I am not experiencing any such thing after turning off v-sync. I also have a powerful modern hardware. Is it dependent on OS or SDL version? I am running Windows 10.

**Comment by lethal-guitar** [comment]
Huh, odd.. :thinking: I don't have access to my machines until next week, so I can't check right now, but I've observed this on both Windows 10 and OS X (high FPS in-game as well). Are you running a Debug or Release build?

**Comment by lethal-guitar** [comment]
Ok, so I'm on Windows 10 Home, Version 1903 (Build 18362.295). I'm running version 417.71 of the NVIDIA drivers. Without v-sync, I get about 3000-4000 FPS in the menus, and 2000+ in-game.
