### ISSUE TITLE
Implement Gamepad support

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#410]
At the moment, RigelEngine only supports keyboard controls. This issue is about adding gamepad support using the [SDL Gamecontroller API](https://wiki.libsdl.org/CategoryGameController). Most of the relevant code is in [`GameRunner::World::handlePlayerInput`](https://github.com/lethal-guitar/RigelEngine/blob/8a53940b01e1f4ee236cc6439f95291245bb3195/src/game_runner.cpp#L375).

Once the game works with controller inputs, it would be great if the menus could also be navigated using a controller. For that, see:

* [DukeScriptRunner::handleEvent](https://github.com/lethal-guitar/RigelEngine/blob/8a53940b01e1f4ee236cc6439f95291245bb3195/src/ui/duke_script_runner.cpp#L158): Handle directional inputs, as well as "A" for enter and "B" for Escape
* [EpisodeEndScreen::handleEvent](https://github.com/lethal-guitar/RigelEngine/blob/0e579c52c277d92f6f64bd94c69022f75b06e4b6/src/ui/episode_end_sequence.cpp#L88): Any button press should be treated like a keypress, and advance to the next image
*[IntroDemoLoopMode::handleEvent](https://github.com/lethal-guitar/RigelEngine/blob/0e579c52c277d92f6f64bd94c69022f75b06e4b6/src/intro_demo_loop_mode.cpp#L92): Here, we'll want to handle any button press for the `if (mCurrentStage == 0)` case as if a key was pressed. For the other case, we'll want to handle the "B" button like Escape.

_Note_: The options menu is handled by Dear ImGui, and enabling Gamepad support for that is a separate issue, as it needs to be done differently.

**Comment by pratikone** [comment]
Can it be tagged as good first issue given it doesn't require much knowledge of the codebase ?

**Comment by lethal-guitar** [comment]
@pratikone yeah good point, I think it can! I'll also add a bit of info soon.
