### ISSUE TITLE
Add key to take screenshot

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#412]
Add a key to take a screenshot (`glReadPixels`) and write it to a PNG file. F12 seems like a good candidate. But maybe best if it's configurable along with other keybindings.

Open question: Where to save the files? User's home directory?

**Comment by pratikone** [comment]
Given that the user will have to do entire process of copying RigelEngine.exe to same directory as the game or provide path to it, it would be good to make a screenshots sub directory in the same directory. It would be most visible to the user and as you won't have to worry about permissions to write to any other directory.

**Comment by lethal-guitar** [comment]
That would be an option as well, and I agree on the discoverability aspect. In the future, I'm planning to ship App Bundles on OS X and Deb packages on Linux, and for those platforms, writing to the executable directory is not permitted, so we still need something different there.

Maybe one solution could be to display the path where screenshots go somewhere in the options menu? If #413 is done first and with using an in-game UI, we might even have the user choose it.

**Comment by pratikone** [comment]
That is definitely a good idea. I like how having #413 will solve many problems. Some of the other recent webassembly ports of retro games allow user to directly download the shareware version within the game(I will try to find an example). Can we do the same thing here without breaking any copyright laws ?

**Comment by lethal-guitar** [comment]
> Can we do the same thing here without breaking any copyright laws ?

Good question! I don't know for sure, and I have deliberately avoided shipping any content with RigelEngine so far to sidestep any issues of this kind. But I also can't really imagine why having the ability to download the shareware version automatically would be a problem. Worth doing a bit of research on I guess!
