### ISSUE TITLE
Build (universal) binary packages for Linux

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#419]
Thanks to @bencsikandrei, we now have `.deb` packages.

In order to have a package that can run on a wider variety of distros, it would be cool to have one (or multiple) of AppImage, Snap or Flatpak as well.

Note: Flatpak has been started (see comments below).

**Comment by Calinou** [comment]
I started working on a Flatpak: https://github.com/Calinou/io.github.RigelEngine

It builds and runs, but it can't find game data currently.

**Comment by lethal-guitar** [comment]
@Calinou awesome, thanks a lot for your work! I'll test it as soon as I can.

> Ideally, it would be better if the user could drop data into a specified location in advance, and the game wouldn't ask for the game data path.

It's possible to specify the game path as command line argument when launching the game, and it won't ask for it in that case. Is there a way with Flatpak to include some kind of launch script maybe? That could make the fixed location work

**Comment by Calinou** [comment]
> Is there a way with Flatpak to include some kind of launch script maybe? That could make the fixed location work

Sure :slightly_smiling_face: I can make it work out of the box then.

**Comment by lethal-guitar** [comment]
We have an icon and a `.desktop` file now: https://github.com/lethal-guitar/RigelEngine/tree/master/dist/linux

Still working on the metainfo xml file.

Also worth noting, Boost is now an optional dependency, so the build could be simplified a bit now.

**Comment by lethal-guitar** [comment]
Hey @Calinou, as of #852, we now have a metainfo xml file. I also continued working on the flatpak file, did some more testing, and I think it's ready now to be submitted to flathub. I'll make a PR shortly.

Thanks again for your work on getting this started!

**Comment by lethal-guitar** [comment]
https://github.com/flathub/flathub/pull/3170

**Comment by lethal-guitar** [comment]
Now published on flathub: https://flathub.org/apps/details/io.github.lethal_guitar.RigelEngine

**Comment by pizzadude** [comment]
Nice! I wouldn't of heard of this if it weren't for you submitting it to flathub.

**Comment by lethal-guitar** [comment]
@pizzadude happy to hear 🙂
