### ISSUE TITLE
WebAssembly port of the game

### ISSUE THREAD

**Issue by pratikone** [lethal-guitar/RigelEngine#421]
WebAssembly is now supported for all the browsers. Many popular libraries including SDL have webassembly [support](https://lyceum-allotments.github.io/2016/06/emscripten-and-sdl-2-tutorial-part-1/).  Many older complex 3D games have been ported to WebAssembly like [Unreal Tournament](https://icculus.org/ut99-emscripten/) and [Doom 3](continuation-labs.com/d3wasm/). Rigel Engine is very modern codebase with major dependency only on SDL (which already has a webassembly port), so we should try to see if it can be ported to WebAssembly. In that way, the game can be distributed by just pointing to URL.

**Comment by lethal-guitar** [comment]
Yeah, this would be sweet! :+1:

**Comment by lethal-guitar** [comment]
@pratikone thanks to your efforts, we can now close this one :slightly_smiling_face: :+1:
