### ISSUE TITLE
cling based C++ as scripting language / hot code reload

### ISSUE THREAD

**Issue by blockspacer** [lethal-guitar/RigelEngine#427]
cling based C++ as scripting language / hot code reload
Why? Able to run C++ script in runtime or compile it for max speed ( as in example https://github.com/derofim/cling-cmake )

> **HOT code reload**
> possible approaches:
> 
> store app state
> fix cling undo for files
> https://root-forum.cern.ch/t/loading-unloading-class-as-interpreted-macro-in-cling-multiple-times/32976/2
> 
> execute cling code to change callbacks & variables
> nested cling::Interpreter with multiple cling::MetaProcessor
> IDK how to do it, but you can create child cling::Interpreter

**Comment by lethal-guitar** [comment]
Hi @blockspacer, welcome to RigelEngine!

That's an interesting idea. I've actually considered integrating a scripting language for quick game logic development a few times, but so far, having everything in C++ works great. I didn't think about using Cling though! Hot reloading does seem quite nice.

It's not totally clear to me which parts of the code would/should support this. Did you have something specific in mind, like game logic, UI code etc.?

There's also the question of dependencies. The project is fairly lean right now, depending only on Boost and SDL in terms of external dependencies. If I understand correctly from looking at the example you've linked, using Cling would require depending on llvm, which seems quite heavy. But that might be ok if it's an optional dependency.

In any case, those are my immediate thoughts - I'm definitely happy to learn more about the advantages of this, and I'll have a closer look at that project you linked to. Thanks for sharing!

**Comment by blockspacer** [comment]
@lethal-guitar 

> There's also the question of dependencies. 
You can also use Cling only in your dev env (optional dependency), so no deps/size overhead for end users. Just wrap your existing app loop into Cling`s main() and you will be able to code in C++ without compilation time. You even can implement live code reload by storing app state/wrapping not whole app/another approach.

End user usually can`t modify scripts. Some apps may benefit from script-to-native 'conversion'.
Develop much faster with Cling help (dev/debug build), release same code compiled without Cling at all (release build).

Also: you can embed Cling for some platforms even in release build, if you want.

**Comment by lethal-guitar** [comment]
Going to close this for now. While it sounds interesting, my focus is on other things. Of course, if someone wants to give it a shot, PRs are always welcome :slightly_smiling_face:
