### ISSUE TITLE
Handle in-game menu via game mode machinery

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#434]
Currently, the in-game menu is Implemented as part of `GameRunner`. We could extend the game mode management to provide a "mode stack" concept. This would allow us to implement the in-game menu as a game mode instead.

Needs some thinking/design.

**Comment by pratikone** [comment]
Happy for this issue. Mode stack concept should reduce code complexity IMO. So, a double win.
