### ISSUE TITLE
Game pad support: Detect controllers being plugged in/out

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#485]
Right now, the game only looks for available game controllers once at startup.

When a controller is unplugged (maybe because the battery dies), the game won't detect it anymore even if it is plugged in again. Same for plugging in a controller while the game is already running.

It would be nice if the game would re-detect available controllers in these situations.

**Comment by pratikone** [comment]
I agree that's one case I thought as nice to have and left it as too much work 😅. a really good implementation of this will indicate when the game detects a game controller, like a small notification popup within the game or an icon like most conventional games of modern times.

**Comment by lethal-guitar** [comment]
Yeah, the indication would be the ultimate version ☺️ But re-detecting would already be a good intermediate step I think.

Seems we could use https://wiki.libsdl.org/SDL_ControllerDeviceEvent
