### ISSUE TITLE
Game pad support: Shooting/jumping via triggers

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#486]
Right now, the left/right bumper buttons (LB/RB) can be used for jumping/shooting in addition to A and X. For me personally, I like using the trigger buttons (LT/RT) more. It would be nice if these would also trigger the respective actions (in addition to LB/RB)

**Comment by pratikone** [comment]
I echo the same sentiments. while implementing game controller support, i didn't find a straightfoward way to support triggers (LT/RT). there was no enum for it. i suppose it is part of more specialized set of buttons that what game controller api expects. hence, i left it then.

**Comment by lethal-guitar** [comment]
I remember reading somewhere that SDL treats the trigger buttons as axis, not as buttons for some reason. Maybe that's useful
