### ISSUE TITLE
Modding support : Resource browser

### ISSUE THREAD

**Issue by pratikone** [lethal-guitar/RigelEngine#497]
It will greatly help in modding if a person is able to browse and extract resources from NUKEM2.CMP. We already have the code to extract and show it within the game. It would be easier to just have a Resource browser executable which can show it easily to the user outside of the game and allow one to save them in a different but accessible file format.

**Comment by lethal-guitar** [comment]
Yep, that would be quite useful indeed! The reason I haven't included any such tool yet is that there already exist various game modding tools which support Duke Nukem II's file formats, for example:

* [Wombat Game Tools](https://szevvy.com/)
* [Camoto](http://www.shikadi.net/camoto)
* [Duke2Edit](http://k1n9duk3.shikadi.net/duke2edit.html)

These tools are quite fully featured and provide nice user interfaces. While we have all the necessary code in RigelEngine to work with the data, we don't have any of the UI yet. Reaching the level of usability provided by these tools would be quite a bit of work, I think. On the other hand, none of these tools support Mac OS as far as I know, and only Camoto runs on Linux, so having a truly cross-platform tool would also be nice. Using ImGui, developing GUIs is quite fast, so I might be overestimating the amount of effort required.

Maybe for now, we could mention these external tools in the README, and leave this issue open to see how much interest there is in a native resource browser tool as part of the project?
