### ISSUE TITLE
Feat. req. Godmode cheat

### ISSUE THREAD

**Issue by necros2k7** [lethal-guitar/RigelEngine#505]
subj

**Comment by necros2k7** [comment]
F12 would be fine I think)

**Comment by lethal-guitar** [comment]
@necros2k7 check out #507. Here's a build: 
https://ci.appveyor.com/api/buildjobs/o9w2vwlhwsqxw6di/artifacts/rigel_build.zip

**Comment by necros2k7** [comment]
Thanx!
