### ISSUE TITLE
CMake fails to find Boost on Fedora 31

### ISSUE THREAD

**Issue by Calinou** [lethal-guitar/RigelEngine#522]
**OS:** Fedora 31
**CMake version:** 3.17.2
**Boost version:** 1.69.0
**RigelEngine version:** https://github.com/lethal-guitar/RigelEngine/commit/d5b171ed95381b4900cd26691f75c0b6c8a4cf3a

After installing `boost-devel` and `boost-program-options`, I get the following error when running CMake:

```text
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Boost (missing: program_options) (found suitable version
  "1.69.0", minimum required is "1.65")
```

I tried to change the required version in `CMakeLists.txt`, but it still didn't work.

**Comment by lethal-guitar** [comment]
Thanks for reporting! I'll investigate later.

In the meantime, if you don't need command line args (they are mainly needed for debugging at this point), you could locally patch out the `program_options` dependency as follows:

* Remove the `COMPONENTS program_options` part from `find_package(Boost` in `CMakeLists.txt`
* Remove the `program_options.hpp` include from `src/main.cpp`
* Replace the main function (same file) with the following:

```cpp
int main(int argc, char** argv) {
  showBanner();

  CommandLineOptions config;
  gameMain(config);
  return 0;
}
```

**Comment by lethal-guitar** [comment]
@Calinou I've got it to work now by additionally installing the `boost-static` package. Let me know if that fixes it for you as well! I'll also update the README to mention this.

**Comment by Calinou** [comment]
@lethal-guitar It works, thanks!
