### ISSUE TITLE
New path for Duke Nukem 2 shareware

### ISSUE THREAD

**Issue by pratikone** [lethal-guitar/RigelEngine#529]
The 3d realms legacy site doesn't seem to allow one to download Duke Nukem 2 shareware. I don't know if it is a temporary problem or a permanent one. hence, I suggest changing this instruction in README to point to archive.org link : https://archive.org/details/msdos_DUKE2_shareware

**Comment by lethal-guitar** [comment]
Ah, good catch! It's probably a good idea in general to link to archive.org, as it's likely to be more stable.
