### ISSUE TITLE
Record a new showcase video 

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#536]
The video linked from the README is quite outdated, showing version 0.4.0. We should record a new showcase video, which shows off some of the registered version levels, the options menu, the wide-screen mode etc.

**Comment by pratikone** [comment]
yay, new video looks awesome and shows all the features. I noticed that in future updates, we can highlight that how this is not running within dosbox but natively multi-platform on Windows, Linux and MacOs. I know that is kind of obvious to visiting the github page but not to those to whom the video will be shown

**Comment by lethal-guitar** [comment]
Good idea! For now, I've added a note to the description of the video.
