### ISSUE TITLE
Opening the options menu crashes on some Windows 7 systems

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#541]

**Comment by lethal-guitar** [comment]
@pratikone do you happen to have a Windows 7 machine around by any chance?

Unfortunately, OpenGL 3.0 is not supported when running in a VM, so I can't test it that way. I have an old PC somewhere that I could install Windows 7 on, but it would take some time to get it up and running.

**Comment by pratikone** [comment]
Sadly no.  All my systems have Win10. I can see if I can find it working in Hyper-V. Do we have some kind of stacktrace ?

**Comment by lethal-guitar** [comment]
> Do we have some kind of stacktrace ?

Unfortunately not. I saw a comment on the YouTube video about this, and someone mentioned it in a forum thread. Most likely these users are not developers, so I wouldn't ask them to install a development environment etc. 

Is there a way to get some kind of crash dump on Windows, that users could send in?

**Comment by lethal-guitar** [comment]
I got an old PC back in working order, installed Windows 7 on it, and tried it. But I cannot reproduce the problem, the game runs fine and the options menu also works without any issues.

The only possible explanations for the problem that I can think of right now:

* Problems with the graphics driver which are triggered by some OpenGL call that ImGui uses but the rest of RigelEngine doesn't
* Users manually copying VS runtime DLLs instead of installing the redistributable, causing incompatibilities that are triggered by something ImGui does.

I replied to the comment on YouTube with corresponding suggestions, let's see if I hear back from them.

**Comment by pratikone** [comment]
Yeah, good idea. just delivering the  zips will bring its own set of problems like mismatched dll, localisation issues, access denied problems, driver issues etc, but again that is part of the process, to make it accessible even to the people who are not technically inclined

**Comment by lethal-guitar** [comment]
It's been a while, and I have not gotten any new information.
