### ISSUE TITLE
Cosmo's Cosmic Adventure support

### ISSUE THREAD

**Issue by jschwartzenberg** [lethal-guitar/RigelEngine#542]
Apparently the Duke Nukem 2 engine was based on the engine of Cosmo's Cosmic Adventure:
http://www.shikadi.net/moddingwiki/Duke_Nukem_II

Has support for the Cosmo been considered?

**Comment by lethal-guitar** [comment]
Indeed, there are quite a few similarities. A lot of the core engine could probably be reused. All the game logic (enemy behaviors, player movement etc.) would have to be newly written, though - and reverse engineered first. I personally don't plan on doing that, but would be happy if my project could serve as the foundation of a Cosmo reimplementation, of course :slightly_smiling_face: 

There is a (unrelated) Cosmo project already: https://github.com/yuv422/cosmo-engine
It seems there is no Linux support yet, though, and I don't know how complete it is.

**Comment by jschwartzenberg** [comment]
I was not aware of this engine!! I just tried it out but it actually seems to run fine at least on Ubuntu 18.04 and it looks quite complete too! I'm sitting on a notebook now that seems to have better OpenGL support though, I'll have to try it on my other notebook to compare with RigelEngine :)

**Comment by jschwartzenberg** [comment]
Yeah it also runs on my OpenGL handicapped notebook ;)
I just ran into a segfault in the bonus level though...

**Comment by lethal-guitar** [comment]
Cool! I think I'll add a link to that project to Rigel's README. I'll close this issue once that's done.
