### ISSUE TITLE
Walking turkey not animated

### ISSUE THREAD

**Issue by rueter37** [lethal-guitar/RigelEngine#543]
Turkeys who walk around show only the first animation frame.

**Comment by lethal-guitar** [comment]
@rueter37 thanks for reporting! I'll look into it. Must have broken recently.

**Comment by lethal-guitar** [comment]
@rueter37 should be fixed now. Thanks again for reporting this! Turns out it was already broken for a really long time (even before , and I never noticed :open_mouth: You can't see the forest for the trees sometimes I guess.
