### ISSUE TITLE
Gamepad support: Allow remapping buttons/axis

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#554]

**Comment by mgtroyas** [comment]
Please consider also mapping to mouse buttons, for instance on my 5 buttons mouse (G203) I usally map quickload an quicksave to the extra ones.

**Comment by lethal-guitar** [comment]
@mgtroyas thanks for the suggestion! I'm happy to do that but I was wondering how that would work since the game has no mouse controls? Would you use the keyboard for movement/shooting and use the mouse for quick save/quick load?

**Comment by mgtroyas** [comment]
Oh, you are absolutely right! My bad, I was thinking on other source ports where mouse is needed like Open Dune, Quakespasm or GZDoom, there's not much advantage doing so here, at least for the standard user case.
