### ISSUE TITLE
Webassembly: Set up hosted version

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#572]
We'd like to have a publicly accessible website with a Wasm build of Rigel running with the Shareware data.

**Comment by lethal-guitar** [comment]
The latest build is now live at https://rigelengine.nikolai-wuttke.de

Thanks to @antongulenko for hosting!

**Comment by pratikone** [comment]
It is throwing connection untrusted error on visiting. On continuing on that I get a 404 error

**Comment by antongulenko** [comment]
I am currently fiddling with the deployment, I will post when it is back online. Thanks for testing!

**Comment by pratikone** [comment]
Looking forward to see my  original vision of getting it to run on a website realized . @lethal-guitar i know you are busy fixing a lot of things but once this gets up and running, you should definitely do a showcase post for social media

**Comment by antongulenko** [comment]
@pratikone It should be back up now - with valid TLS certificates and everything. If you get the chance to test, let me know if there are hosting issues.

**Comment by lethal-guitar** [comment]
@pratikone 

> once this gets up and running, you should definitely do a showcase post for social media

Will do ☺️

**Comment by lethal-guitar** [comment]
@pratikone most issues have been fixed in the latest deployed version, so this is ready for sharing now! I already tweeted about it and mentioned you in the thread 🙂
