### ISSUE TITLE
Webassembly: Browser intercepts some key events

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#575]
On Windows, pressing `alt` to shoot brings up Firefox' menu, stealing focus from the game.

This is less of a problem now that key bindings can be changed. That's another reason why #573 would be good though, since any custom key bindings are otherwise lost when reloading the page.

**Comment by pratikone** [comment]
That sounds good. Also we can have sensible defaults for shooting and other actions for Wasim build. So that by default alt is not used for shooting.

**Comment by lethal-guitar** [comment]
@pratikone yes, I was thinking about that as well. However, it seems this is not a problem anymore - I was not able to reproduce it, at least, pressing Alt worked fine and didn't bring up the menu.

I'm not sure what fixed it, but I switched to a more recent Emscripten version today so maybe that brought in some improvements
