### ISSUE TITLE
Feature Request path to data

### ISSUE THREAD

**Issue by NeonLightning** [lethal-guitar/RigelEngine#577]
i was wondering how doable sticking the binary in one folder and being able to stick the data files in a different folder is. maybe something like --data-dir=/path-to-/duke2data ?

**Comment by lethal-guitar** [comment]
That's already possible: Either as a positional argument (`RigelEngine /path/to/data`) or `--game-path /path/to/data`.

This was mentioned more prominently in the README originally, until we implemented the game path browser.. I should try to make it more obvious that this is possible.

**Comment by NeonLightning** [comment]
ah i thought i was getting segfaults due to path difference but it turned out to be a bad compile.
