### ISSUE TITLE
Running on Pi4/RetroPie

### ISSUE THREAD

**Issue by Exarkuniv** [lethal-guitar/RigelEngine#605]
I followed your instructions to compile on  a Pi and it worked fine for that part.
but how do i point the RigelEngine to 

    NUKEM2.CMP (the main data file)
    NUKEM2.F1, .F2, .F3 etc. up to .F5 (intro movie files)

so RetroPie does not have a desktop so i would need to do it by command line
I know that RetroPie is Buster Linux 5.4.72

**Comment by lethal-guitar** [comment]
Hi @Exarkuniv, nice to hear that it built successfully for you! You can pass the path to the directory containing those files as positional argument on the command line. So e.g. if you have the files in `/home/pi/Duke2`, you would do `./src/RigelEngine /home/pi/Duke2`. Hope that helps!

**Comment by Exarkuniv** [comment]
Hey @lethal-guitar just wanted to say. what you said works great. 
i have to say it looks just like it did on DOS. you did amazing work with this.
all i need to do is get the runcommand working for the RetroPie software and we be good. 
i just need to remember how i did it for Blood and a few other games that i compiled. 

Thanks again

**Comment by lethal-guitar** [comment]
Hey @Exarkuniv, thanks, my pleasure, and happy to hear that it works! Enjoy the game 🙂
