### ISSUE TITLE
compiling problems on oga

### ISSUE THREAD

**Issue by NeonLightning** [lethal-guitar/RigelEngine#634]
retroroller has been surpassed by rrvl.
i tried to compile it on there but couldn't get it to see sdl2 for some reason.
and i also tried the version i built long ago on retroroller on emuelec but it had some gcc error i think it was.
any chance of putting together a package.mk for emuelec so shanti can include this in emuelec?
this is an example of one.
https://github.com/EmuELEC/EmuELEC/blob/dev/packages/sx05re/emuelec-ports/VVVVVV/package.mk

**Comment by lethal-guitar** [comment]
> i tried to compile it on there but couldn't get it to see sdl2 for some reason.

I've been meaning to try out RRVL 🙂 Let me see, maybe I can figure out how to make it compile on there.

> any chance of putting together a package.mk for emuelec so shanti can include this in emuelec?

Sure, I'd be happy to look into that - would be nice to have the game included there!

**Comment by lethal-guitar** [comment]
@NeonLightning I just tried building on RRVL, and the CMake part worked once I installed all the necessary packages:

* `SDL2_mixer-devel` (will install `SDL2-devel` as well)
* `boost-devel`

Maybe you're missing one of these packages?

The build is still going, I'll let you know how it turned out once it's done.

**Comment by lethal-guitar** [comment]
Hmm, there's still a problem - it's now trying to link SDL statically, which doesn't make sense as it then picks up the wrong version. I'll look into it some more

**Comment by lethal-guitar** [comment]
@NeonLightning in other news: RigelEngine is now in EmuELEC 🎉 
https://github.com/EmuELEC/EmuELEC/pull/398

**Comment by lethal-guitar** [comment]
@NeonLightning I finally managed to make a functioning build on RRVL. So as mentioned before, you need to install `SDL2_mixer-devel`, SDL2-devel` and `boost-devel`. Then, invoke CMake like this:

```bash
cmake .. -DUSE_GL_ES=ON -DCMAKE_BUILD_TYPE=Release -DWARNINGS_AS_ERRORS=OFF -DSDL2_LIBRARY_RELEASE=/usr/lib/libSDL2-2.0.so.0.10.0
```

Hope that works for you, let me know if you still get errors!

**Comment by NeonLightning** [comment]
i'll be trying the newest rrvl later this week hopefully. so i'll give it a shot then.

**Comment by NeonLightning** [comment]
sorry still haven't had a chance and looks like i won't for a bit.(personal problems for the next while)

**Comment by lethal-guitar** [comment]
Hey @NeonLightning, sorry to hear that! No worries, and hope things get better for you soon!

**Comment by lethal-guitar** [comment]
@NeonLightning I'm going to close this issue, since the game has been bundled with EmuELEC now for quite a while and RRVL doesn't seem to exist anymore AFAICT.
