### ISSUE TITLE
Webassembly: Improve welcome message

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#652]
The current welcome message is functional, but not the best looking.. Some ideas on what to improve:

* Rounded corners for the background rectangle
* Better styling for links and the close button
* Adapt to different screen sizes
* Find a way to adjust the width for better looking text layout?

**Comment by pratikone** [comment]
Couple of more points : Put a 1-2 line description of what Rigel Engine project is. Move Controls over Limitations. If you like, you can also mention one or two limitations and then link to a release markdown file with wasm limitations. Also, set a link to your twitter to follow latest updates on it. 
Overall, looks good. HN and Reddit worthy but it can kill the bandwidth though. Share it with LGR :)

**Comment by lethal-guitar** [comment]
@pratikone 
> Put a 1-2 line description of what Rigel Engine project is. Move Controls over Limitations as a typical user would be more interested in that.

Good idea, I'll do that 👍🏻 

> set a link to your twitter to follow latest updates on it.

I'll think about it - I don't expect to do many major updates in the coming weeks but let's see 🙂 

> Share it with LGR :)

Yep - already drafted a mail 🚀 Will send it sometime this weekend probably, after I improve the welcome box a little bit.

**Comment by pratikone** [comment]
that's awesome. we got lucky with Jeff Atwood tweet too :) . he liked it. hoping best for LGR and some good coverage on it.
