### ISSUE TITLE
Design an icon for RigelEngine

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#674]
Now that we're working on more binary distribution options (e.g. #673), it would be nice if the game had an icon we could include with those packages, use as the executable icon on Windows, etc.

It would be nice if it's something reminiscent of the original game but without using any of the original art (to avoid copyright issues). Or maybe a nice stylized "Rigel" logo with some gears or something that looks like "engine".

**Comment by bencsikandrei** [comment]
I'm really not good at this, but I still gave it a go :) 

https://i.imgur.com/wVlDwVl.png

How bad is it?

**Comment by lethal-guitar** [comment]
> I'm really not good at this, but I still gave it a go :)

Nice! I think that's actually a pretty good start! 👍🏻 I like the shape of the font and the gears, and the pixelated style is definitely fitting.

I'm not good with design/art either, one of the things I like about this project is that all the art and game design is already done, and I can focus on programming 😄 

In terms of colors, maybe the font could be made to look somewhat like this:

![grafik](https://user-images.githubusercontent.com/1821027/118364699-d8fcc500-b599-11eb-829c-167c431a331d.png)

And the gears could use some of the gray tones from Duke's palette, similar to this enemy:

![grafik](https://user-images.githubusercontent.com/1821027/118364820-59232a80-b59a-11eb-904f-176e05b10839.png)

> EDIT: I made it in GIMP and can also share the xcf

Sure, why not, I can also try playing around with it a bit!

**Comment by pratikone** [comment]
if any of you work with vector art, it would be simpler to combine few simple shapes to make a logo reminiscent of Duke Nukem II with little art skill (vector shapes can be made by drag and drop of simple shapes)

**Comment by LunarLoony** [comment]
![rigelengine-v1-4x](https://user-images.githubusercontent.com/2440723/126448942-9aa99ccd-42fe-474f-ba62-7249edad0afb.png)

How's this?

**Comment by lethal-guitar** [comment]
@LunarLoony wow that's really awesome, I love it!

**Comment by LunarLoony** [comment]
Great! Is it okay as it is or do you want any changes making?

**Comment by lethal-guitar** [comment]
@LunarLoony I have to see how it looks once I integrate it for the different platforms, but for now it looks perfect. Thank you so much!

How would you prefer to be credited? "Icon by Tim Scott"?

**Comment by LunarLoony** [comment]
LunarLoony will be fine for credit.

I've also exported a few different sizes - 

16px - ![rigelengine-v1](https://user-images.githubusercontent.com/2440723/126453869-d7b02d58-e5f2-46e3-b4e0-8386db886946.png)

32px - ![rigelengine-v1-2x](https://user-images.githubusercontent.com/2440723/126453879-ed73e196-b1d3-46b3-b1fc-92c2f2e13ce3.png)

48px - ![rigelengine-v1-3x](https://user-images.githubusercontent.com/2440723/126453979-3c3891a5-2726-4007-bc28-b32aa4df805d.png)

64px - ![rigelengine-v1-4x](https://user-images.githubusercontent.com/2440723/126453884-d6595c64-b9f2-44e4-b140-930b642de8c2.png)

128px - ![rigelengine-v1-8x](https://user-images.githubusercontent.com/2440723/126453887-e92ec612-7d64-4ea5-abd8-2a35adc68dbb.png)

**Comment by lethal-guitar** [comment]
> I've also exported a few different sizes

Nice! 👍🏻

**Comment by pratikone** [comment]
so happy :) great job on the icon

**Comment by lethal-guitar** [comment]
@LunarLoony successfully integrated the icon into the Mac build 🎉 

![image](https://user-images.githubusercontent.com/1821027/126982208-40c10017-ab2e-492d-a8c8-0a0141bfc57b.png)

Windows and Linux are next. Thanks again for this awesome contribution!
