### ISSUE TITLE
asset error

### ISSUE THREAD

**Issue by Exarkuniv** [lethal-guitar/RigelEngine#687]
@lethal-guitar i have finally gotten around to make a script to build RigelEngine for Retropie nice and easy for me. 

it seems to build with out errors and i have it linked the folder for my Duke files.

when i start the game i see the do not distribute screen then i get this error

filesystem error: directory iterator cannot open directory : no such file or directory [/home/pi/RetroPie/rom/ports/duke2/asset_replacements]

am i missing a file from the build folder. all that i took out of it was the RigelEngine file. 

thanks again for all your amazing work

**Comment by lethal-guitar** [comment]
@Exarkuniv thanks for reporting, this looks like something I caused with a recent change, sorry about that! I'll push a fix ASAP. In the meantime, as a workaround, you can create an empty directory `/home/pi/RetroPie/rom/ports/duke2/asset_replacements` and that should prevent the problem.

**Comment by Exarkuniv** [comment]
@lethal-guitar that's cool. It will have to wait till after the weekend for me to fix it. As my pi is at work. 

But thanks for getting back to me ok this.

**Comment by lethal-guitar** [comment]
> But thanks for getting back to me ok this.

@Exarkuniv no problem 🙂 Thanks again for telling me, not sure when I would have noticed otherwise!

**Comment by lethal-guitar** [comment]
I've merged a fix, let me know if the latest `master` branch works for you.

**Comment by Exarkuniv** [comment]
@lethal-guitar i ran my script again and everything is working perfectly.

thanks again for you help

**Comment by lethal-guitar** [comment]
@Exarkuniv cool, good to hear. Enjoy the game 🙂
