### ISSUE TITLE
Support of Steam version integration.

### ISSUE THREAD

**Issue by KainXVIII** [lethal-guitar/RigelEngine#698]
Right now if you copy files and rename RigelEngine.exe to dosbox.exe and (with needed DN2 data files) - steam version just don't run..Maybe because its trying to run dosbox with these arguments "-conf "..\NUKEM2.conf" -noconsole -c" https://steamdb.info/app/240180/config/ and maybe its somehow conflicts with RigelEngine. Don't know if its possible to fix this, but if possible - this will be very cool!

**Comment by lethal-guitar** [comment]
@KainXVIII you can run use the Steam data files without launching the game through Steam, renaming `RigelEngine.exe` is not necessary. Just run RigelEngine directly and then select the folder where the Steam version is installed when it prompts you for the game files.

I don't have the Steam version of the game myself so I can't test it, but I've heard from people that they were running it successfully.

**Comment by KainXVIII** [comment]
> @KainXVIII you can run using the Steam data files without launching the game through Steam, renaming `RigelEngine.exe` is not necessary. Just run RigelEngine directly and then select the folder where the Steam version is installed when it prompts you for the game files.
> 
> I don't have the Steam version of the game myself so I can't test it, but I've heard from people that they were running it successfully.

I know, but what if i WANT to run DN2 with rigel through steam (for example to share screenshots in steam activity feed, etc..)?

**Comment by lethal-guitar** [comment]
Ohh I see, now I understand! Sure I can look into making it ignore unknown command line options, maybe that makes it work then.

**Comment by KainXVIII** [comment]
> Ohh I see, now I understand! Sure I can look into making it ignore unknown command line options, maybe that makes it work then.

Yeah, something like that!

**Comment by lethal-guitar** [comment]
@KainXVIII it took some time, but here's a build now which ignores all command line arguments in case the exe has been renamed: https://ci.appveyor.com/api/buildjobs/ciarnn7n1hmimhux/artifacts/rigelengine_win_x64.zip

Let me know if that works for you for running the game via Steam!

**Comment by KainXVIII** [comment]
> @KainXVIII it took some time, but here's a build now which ignores all command line arguments in case the exe has been renamed: https://ci.appveyor.com/api/buildjobs/ciarnn7n1hmimhux/artifacts/rigelengine_win_x64.zip
> 
> Let me know if that works for you for running the game via Steam!

Thanks! Works like a charm with Steam version now, overlay also supported!

**Comment by lethal-guitar** [comment]
@KainXVIII cool, happy to hear 🙂 Will close this issue then.
