### ISSUE TITLE
Possible to get Ultrawide on 4K?

### ISSUE THREAD

**Issue by JEmlay** [lethal-guitar/RigelEngine#700]
I saw this running in ultrawide but I see no way to gain an ultrawide aspect ratio on a 16:9 4K monitor (obviously with black bars above and below which is fine.  The game isn't in 4K so I see little point in taking up all of the 4K screen but taking advantage of ultrawide would be useful.

Possible future support?

**Comment by lethal-guitar** [comment]
Hey, thanks for the suggestion! There's been a few people asking for this, it should definitely be possible and I'm happy to look into it 🙂 In the meantime, you could try running in windowed mode and making the window very wide. Also see https://github.com/lethal-guitar/RigelEngine/issues/392#issuecomment-883766332

**Comment by JEmlay** [comment]
WOW!  Yeah, that did the trick.  For some odd reason I had to do WinKey down then up then right then left in order to get the title bar.  Just left or doing right then left wouldn't work.  Weird.

Also have to be careful how narrow I make it otherwise I get "X coord out of bounds".  I went slowly until I got the error and remembered where it last was.  I was able to get 454x3840 which is insane!  Insane Ultra Super Widescreen

Thanks!

**Comment by lethal-guitar** [comment]
> I was able to get 454x3840 which is insane! Insane Ultra Super Widescreen
> 
> Thanks!

Niiice! 😎 

> Also have to be careful how narrow I make it otherwise I get "X coord out of bounds".

Oh that's good to know, that shouldn't happen. I need to fix that. Thanks!
