### ISSUE TITLE
Option to disable fullscreen flashes

### ISSUE THREAD

**Issue by arnoldsecret** [lethal-guitar/RigelEngine#708]
In the original game, whether you destroy a wall, the game screen momentarily flashes white for a bit. This is an annoyance and may cause seizures towards photosensitive people.

Label as usability and enhancement.

**Comment by lethal-guitar** [comment]
@arnoldsecret thanks for your suggestion, that's a good addition! Should be quite easy to implement, too. 👍🏻 I'll aim to get in in the upcoming 0.8 release.

**Comment by lethal-guitar** [comment]
@arnoldsecret here's a build with this option added: https://ci.appveyor.com/api/buildjobs/7gdmepr8d8f691te/artifacts/rigelengine_win_x64.zip

Let me know if that covers what you had in mind 🙂

**Comment by arnoldsecret** [comment]
works as intended, thanks 👍
