### ISSUE TITLE
Keys can be used in midair

### ISSUE THREAD

**Issue by snoopin1** [lethal-guitar/RigelEngine#715]
In RigelEngine, key panels can be activated while Duke is in midair (e.g., from jumping). This will cause Duke to momentarily hover (see screenshot). I have tried to do this in the original game, but it seems the original behavior only allows key panels to be activated if Duke is on solid ground.

![RigelEngine 2021-08-08 16-14-38-64](https://user-images.githubusercontent.com/12336450/128622896-fa57af10-eb77-4358-9e89-5ece0d22a933.png)

**Comment by lethal-guitar** [comment]
Thanks, really appreciate these reports! 👍🏻
