### ISSUE TITLE
Custom refresh rate limit or add 75Hz

### ISSUE THREAD

**Issue by mgtroyas** [lethal-guitar/RigelEngine#788]
I own a 75Hz monitor, but that frequency is not included in the refresh rate limit list (only 70 and 72). Would be great to have an option to have an editable custom refresh rate limit option.

If it's not easy to add, I request adding 75Hz to the list.

**Comment by mgtroyas** [comment]
Ok I found where is the settings file stored, and it can be manually edited.
https://github.com/lethal-guitar/RigelEngine/wiki/FAQ#where-are-saved-games-settings-etc-stored

It's not so convenient but works.

**Comment by lethal-guitar** [comment]
@mgtroyas thanks for the suggestion! Glad you were able to work around it with the options file, but I agree that that's not ideal. I'm happy to add a new entry to the list of available refresh rates, that's very easy to do. Being able to add a custom one is a little more work, but would be the most user-friendly/future-proof for sure. I'll look into it.

**Comment by lethal-guitar** [comment]
@mgtroyas as of the [latest release](https://github.com/lethal-guitar/RigelEngine/releases/tag/v0.8.3), 75 has been added to the list of options. I'm still planning to allow fully custom refresh rates in the UI, but that'll come a bit later so I'll keep this issue open until then.
