### ISSUE TITLE
"Smooth scrolling & movement" has small hiccups

### ISSUE THREAD

**Issue by vanfanel** [lethal-guitar/RigelEngine#792]
Hi there @lethal-guitar 

I am still at awe with the new "Smooth scrolling & movement" option, it's just incredible and the game looks brutally arcade-esque to me now!

However, movement (with VSYNC ON) shows small hiccups once in a while when walking on straight surfaces with no slopes, etc, where movement should be always perfect.

Maybe there's something still being done about the improvement, but I have decided to do this report because it may be easier to fix when the code is still fresh :)

**Comment by lethal-guitar** [comment]
@vanfanel thanks for the report! I've also occasionally seen these kind of hitches, I'll investigate.

**Comment by lethal-guitar** [comment]
Oh and happy to hear you're enjoying the new mode 😃

**Comment by vanfanel** [comment]
Wow! Why is this still open? I have been enjoying perfect scroll for months now... no hiccups anymore!

**Comment by lethal-guitar** [comment]
Happy to hear! 🙂

**Comment by vanfanel** [comment]
This engine is just incredible, @lethal-guitar 
It's very often used by both my gf and me for Duke 2 classic action on the Pi4. And we love it.

**Comment by lethal-guitar** [comment]
@vanfanel that's awesome, thanks for the kind words!
