### ISSUE TITLE
RetroPie install script

### ISSUE THREAD

**Issue by Exarkuniv** [lethal-guitar/RigelEngine#793]
@lethal-guitar 
No issue here. 
I just wanted you to know that i have made a install script for Rigelengine on RetroPie on the Pi4 
[my Github page](https://github.com/Exarkuniv/Rigelengine-RPi) if you want to add it to your Wiki or anything.
it takes all the work out of it. For the RetroPie Pi4 user at least

**Comment by lethal-guitar** [comment]
@Exarkuniv that's awesome, thanks so much for sharing! I'll add it to the Wiki page about Raspberry Pi.

**Comment by lethal-guitar** [comment]
I'm now linking to your repo from the build instructions and from the wiki page. I've also tested it on my Pi 3 B, and it works perfectly on there too  👍🏻🙂

**Comment by Exarkuniv** [comment]
@lethal-guitar :) 
cool
im glad that it works on the Pi3. 
glad you thought of doing that. lol

**Comment by lethal-guitar** [comment]
See https://github.com/RetroPie/RetroPie-Setup/pull/3448
