### ISSUE TITLE
Consistent spelling: `Viewport` instead of `ViewPort`

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#795]
Spelling of the word "viewport" is inconsistent in the code, sometimes it's spelled `viewPort` and sometimes `viewport`. It would be nice to make it consistent.

**Comment by mohitsaxenaknoldus** [comment]
Can I work on this?

**Comment by lethal-guitar** [comment]
@mohitsaxenaknoldus of course, go for it! 🙂

**Comment by mohitsaxenaknoldus** [comment]
So we want `Viewport` or `ViewPort`?

**Comment by lethal-guitar** [comment]
`viewport` with a lower-case "p".

**Comment by mohitsaxenaknoldus** [comment]
PR: https://github.com/lethal-guitar/RigelEngine/pull/812
