### ISSUE TITLE
Rename `math_tools.hpp` -> `math_utils.hpp`

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#806]
For consistency with other filenames.

**Comment by mohitsaxenaknoldus** [comment]
Can I work on this?

**Comment by lethal-guitar** [comment]
@mohitsaxenaknoldus absolutely, go for it 👍🏻🙂

**Comment by mohitsaxenaknoldus** [comment]
Thanks! PR: https://github.com/lethal-guitar/RigelEngine/pull/811
