### ISSUE TITLE
Add a `format-staged.sh` script

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#815]
Currently, we have `tools/format-all.sh` to run clang-format on the code. Formatting all of the code can take a bit of time though. It would be handy to additionally have a 2nd script which runs clang-format only on files that are currently staged in git.

**Comment by mohitsaxenaknoldus** [comment]
Please assign it to me, I'll do it.

**Comment by lethal-guitar** [comment]
@mohitsaxenaknoldus thanks, it's all yours

**Comment by mohitsaxenaknoldus** [comment]
Thanks! @lethal-guitar 
PR: https://github.com/lethal-guitar/RigelEngine/pull/824
