### ISSUE TITLE
Move `data/image.{hpp|cpp}` to `base`

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#817]
Move the files `image.hpp` and `image.cpp` from `src/data` to `src/base`, adapt all include statements in client code and update `CMakeLists.txt`.

**Comment by naftalimurgor** [comment]
Hello @lethal-guitar 
Seems like something we can work out. Will submit a PR for this once it's ready 

Best,
Naftali

**Comment by lethal-guitar** [comment]
Awesome, looking forward to the PR! 👍🏻

**Comment by naftalimurgor** [comment]
Hello @lethal-guitar 
Check this out #863 Let me know in case of any other changes to add on!
Best,
Naftali
