### ISSUE TITLE
Rename `loader` to `assets`

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#819]
1. Rename the directory `src/loader` to `src/assets`, adapt all includes in client code and update the CMake file.

2. Rename the namespace `loader` to `assets`

**Comment by naftalimurgor** [comment]
Hello @lethal-guitar 

This sounds like something I can help with. I've no prior experience with game engines and this might be a great way to get involved. Let me know if there is anything other things I might need to get started with this issue

Thanks  & happy new year!

**Comment by lethal-guitar** [comment]
Hi @naftalimurgor, happy new year and welcome to the project! 👋🏻 Sure thing, I believe this issue should be fairly straightforward and you don't need any specific prior knowledge, so it's a good way to get a first look at the code.

A few things might be helpful to know: We use GitHub Actions for CI, so when you open a PR you'll be able to see if the code still compiles fine for all the platforms after your changes. Also worth noting is that we use clang-format for automatic code formatting, and this is also checked on CI. You can find more information on how to set up and run the formatter [here](https://github.com/lethal-guitar/RigelEngine/blob/master/CONTRIBUTING.md#code-formatting).

If you want to dig deeper into the architecture of the code, [the wiki](https://github.com/lethal-guitar/RigelEngine/wiki/Architecture-overview) also has a good bit of info. It's not quite complete yet but should give a good high level picture.

Happy to answer any further questions you have 🙂

**Comment by naftalimurgor** [comment]
Hi @lethal-guitar 
Thanks for warm welcome 😄 . I've no further questions.  Will stop by in case of any challenges.

**Comment by naftalimurgor** [comment]
Hi @lethal-guitar 
Greetings! I'm done working on this issue!

I'm using an older version of the Ubuntu distro(Ubuntu 16.04), I ran into issues with `clang-format-version` I currently have a slightly higher version of `clang-format-11` It's `clang-format-11.10.0`

 I can't seem to be able to install the version specified in `tools/format.sh`

How can I resolve this?

Thanks!

**Comment by lethal-guitar** [comment]
Hi @naftalimurgor, nice one! 👍🏻 Hmm, that's interesting.. I have never encountered a clang-format version with a minor version other than 0 before. There are two options:

* We could try and see if the formatting is correct with your version, since it's still the same major version.
* You could run clang-format via Docker, as described in the contribution guide.

For the first option, I've just pushed a branch called `relax-clang-format-version-check` which changes the script so that it should also accept your version. So you could grab the script from that branch, format your code, create your PR, and then we will see if CI accepts the formatting.

Apply the following patch

**Comment by naftalimurgor** [comment]
Hello @lethal-guitar 

Let's go with option 1.  Currently, I don't have Docker set up yet. If CI does not accept the formatting we'll go with the latter,  set up Docker and format using the current version then resubmit the PR.

**Comment by naftalimurgor** [comment]
Hello @lethal-guitar
 
I checked last night and I think I was using a lower version of `clang-format` which was causing the formating to halt. I changed to `clang-format-11.1.0`. It was nothing to do with `clang-format-11` having a higher minor version.

 I also updated the PR to fix the failing CI checks.

**Comment by lethal-guitar** [comment]
Hi @naftalimurgor great, just had a look at the PR, it all looks good thanks.

> It was nothing to do with clang-format-11 having a higher minor version.

Hm, without my changes to the formatting script it would reject version `11.1.0` though, because the check was too strict (looking for an exact match of `11.0.0`). So I'm still going to update the script to make the check a bit less restrictive, since CI was happy with your formatting and so it seems that the behavior doesn't change between minor versions, just major versions.

**Comment by naftalimurgor** [comment]
Great, I'm still new to modern C++ and as I was working on this I had this question: Is it possible to have a forward declaration of a class inside another namespace of the same name: Example in pseudocode:
```c++
namespace rigel::loader {
    ResourceLoader::someMethod() {}
}

// somewhere else, a forward declaration, in a different namespace with same name as loader:
namespace loader {
    class ResourceLoader;
}

// example usage 
const mResource& loader::ResourceLoader;
```
I'm new to C++ and that had me thinking.

**Comment by lethal-guitar** [comment]
Yes, that's totally possible, as long as the name of the namespace matches - including any potential surrounding namespaces. So to go with your example, if the namespace where the class is properly declared is `rigel::loader`, then the forward declaration also needs to be in a namespace `rigel::loader`, otherwise the name will be considered not matching. It can be done either via the `namespace rigel::loader` syntax which is new in C++ 17, or it can also be done with multiple nested namespace declarations like so:

```cpp
namespace rigel
{

// potentially some other code here

// effective name of the namespace is now rigel::loader,
// since it is defined within a namespace called rigel
namespace loader 
{

class ResourceLoader;

}
}
```

But yeah, as long as the full name of the namespace including all parent namespaces matches, it's considered "the same" as another namespace defined in another file. And that means we can do forward declarations.

What would *not* work is to have the namespace just be called `loader` without the parent `rigel` namespace.

Hope that answers your question!

**Comment by naftalimurgor** [comment]
Yes, That answers my question perfectly. Thank you!
