### ISSUE TITLE
Make the smooth scrolling option affect the radar view

### ISSUE THREAD

**Issue by Calinou** [lethal-guitar/RigelEngine#834]
Right now, the smooth scrolling option does not affect the radar view, which still updates at 15 FPS. While this does not *always* result in visible jittering, jumping objects can travel more than one tile per game tick. In this case, interpolation would be beneficial to improve smoothness, even on a 60 Hz monitor.

This is arguably very low priority, but it'd be nice to have to further polish the experience.

**Comment by lethal-guitar** [comment]
Totally! 👍🏻 I'll give it a look next time I'm working on smooth scrolling, thanks!
