### ISSUE TITLE
[Windows] Executable fails to start if in a directory with spaces or symbols

### ISSUE THREAD

**Issue by hfc2x** [lethal-guitar/RigelEngine#848]
Pretty much what says in the title. My Duke 2 folder is within a long string of folders with symbols and spaces (and swearing), therefore RigelEngine starts out with an error that NUKEM2.CMP can't be opened.

**Comment by lethal-guitar** [comment]
@hfc2x thanks for reporting! Spaces are not a problem, but I can reproduce the issue when using a path with emoji and other special characters. I'm investigating!

**Comment by lethal-guitar** [comment]
@hfc2x Ok, this should fix it:

[RigelEngine_unicode_path_fix.zip](https://github.com/lethal-guitar/RigelEngine/files/8668653/RigelEngine_unicode_path_fix.zip)

Can you give this a try and let me know if it fixes the problem for you as well? Note that you might have to delete the user profile file, if RigelEngine has already created one. See https://github.com/lethal-guitar/RigelEngine/wiki/FAQ#where-are-saved-games-settings-etc-stored

This is the path I tested with, which is now working:

![grafik](https://user-images.githubusercontent.com/1821027/167818790-8534f5c2-cb81-47a5-9f3f-90dfa2fccad7.png)

**Comment by hfc2x** [comment]
Yes! That actually fixed the problem.
