### ISSUE TITLE
Junk files?

### ISSUE THREAD

**Issue by necros2k7** [lethal-guitar/RigelEngine#853]
These dlls come with latest build:
libFLAC-8.dll
libmodplug-1.dll
libmpg123-0.dll
libogg-0.dll
libopus-0.dll
libopusfile-0.dll
libvorbis-0.dll
libvorbisfile-3.dll
App runs fine without them.
Are they ok to delete?

**Comment by lethal-guitar** [comment]
Hi @necros2k7, these files are there to support different replacement music file formats for the extended modding support (see https://github.com/lethal-guitar/RigelEngine/wiki/Modding-support). The game will run without them, but replacement music will not work

**Comment by necros2k7** [comment]
OK
