### ISSUE TITLE
Rename `PlayerModel` -> `PersistentPlayerState`

### ISSUE THREAD

**Issue by lethal-guitar** [lethal-guitar/RigelEngine#878]
* Rename the class `PlayerModel` (declared in `src/data/player_model.hpp`/`.cpp`) to `PersistentPlayerState`
* Rename variables of type `PlayerModel` or `PlayerModel*` accordingly. For example, rename `mpPlayerModel` -> `mpPersistentPlayerState`, `pPlayerModel` -> `pPersistentPlayerState`, etc.

**Comment by naftalimurgor** [comment]
Hey @lethal-guitar 
How are you doing? I want to take on this. Perhaps you can give a brief description/summary of what needs to be done

Thanks

**Comment by lethal-guitar** [comment]
Hi @naftalimurgor, I'm doing alright thank you, hope you're doing well too!

Sure thing, I've updated the description of the issue. Let me know if that's enough information!

**Comment by naftalimurgor** [comment]
Hi @lethal-guitar 
I'm doing great thanks! I'm on it. The description is great. I'll update the issue thread if I need further assistance
Thanks
