### ISSUE TITLE
[3ds] Any port ?

### ISSUE THREAD

**Issue by soaresden** [lethal-guitar/RigelEngine#907]
Hi ! 
Love Duke Nukem II and it's so great soundtrack.
I think the 3DS is the best choice to replay this game !
Any possibility to port it ?

Thanks !

**Comment by lethal-guitar** [comment]
Technically, it's certainly possible. But I don't own a 3DS and I don't have any experience developing for that platform. Plus it doesn't look like it has full OpenGL ES support, from a brief search. So there would be a pretty significant amount of work involved to rewrite the renderer.

So realistically, I don't think this is something I can do for the foreseeable future. But if someone else wants to take it on, then I'd be happy to support that in any way I can.
