### ISSUE TITLE
Portable Install

### ISSUE THREAD

**Issue by AskaLangly** [lethal-guitar/RigelEngine#908]
Since the player's files are stored in `%appdata%\Roaming`, could it be possible to add a `portable.txt` in the game's root, in order to load the user's files from a `~/userdata` directory instead? I understand it wouldn't be beneficial for, say, Steam Deck, but it would be nice to have as an added convenience.

**Comment by lethal-guitar** [comment]
@AskaLangly yeah can do, that's an easy change. Just to clarify, the `userdata` directory would then also be next to the game files? So for example, if you had a Duke 2 installation at `C:\Games\Duke2`, then both the `portable.txt` file as well as the `userdata` directory would also be in `C:\Games\Duke2`? Or would `userdata` be in the user directory (i.e. `C:\Users\<name>` on Windows)

**Comment by AskaLangly** [comment]
`C:\Games\Duke2\userdata\`
...
`C:\Games\Duke2\portable.txt`

`portable.txt` would be zero bytes; game's looking for the file by name only.

**Comment by lethal-guitar** [comment]
Hi @AskaLangly, I've implemented a first version of this and made a build for you to test: https://ci.appveyor.com/api/buildjobs/4hk62nw0gt4ejt53/artifacts/rigelengine_win_x64.zip

Let me know if it works like you expect.

**Comment by AskaLangly** [comment]
Hello! It works as I imagined it would.

First, I made sure that this build still used AppData, and it read my current save.
Then, I created the `portable.txt`. Before migrating the data over, I let the game create directories; saw `userdata` pop up.
Then, I overwrote what it created with my current save, and it all works.

**Comment by QmwJlHuSg9pa** [comment]
Related: It would be neat if there were an environment variable to explicitly set the game data directory, in case the game files had already been placed elsewhere.

For instance, Flatpak apps and installed games (e.g. Lutris, Steam) may be kept on separate drives.

**Comment by lethal-guitar** [comment]
@QmwJlHuSg9pa it's already possible to do that by passing the game path as a command line argument:

`RigelEngine <path-to-game>`

**Comment by roioros** [comment]
Hi!

Would it be possible for you to reupload the version that has support for use it in portable mode?

The link above is no longer available.

Thank you!!

**Comment by Nutzzz** [comment]
> Would it be possible for you to reupload the version that has support for use it in portable mode?

This was implemented already. Just put a blank file called portable.txt in the same folder.

**Comment by lethal-guitar** [comment]
It has been implemented indeed, but the changes aren't in the latest release yet, so building from source is currently required. I can upload a new build.

**Comment by lethal-guitar** [comment]
@roioros here's a new link: https://ci.appveyor.com/api/buildjobs/34c7hvrl3it8erk2/artifacts/rigelengine_win_x64.zip
It should be valid for 1 month.

I'll see if I can create a new release soon with the two latest additions (portable mode, and game path in options).

**Comment by roioros** [comment]
Great!

Thank you so much!!  ;)
