### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by orderorder** [lethal-guitar/RigelEngine#914]
RigelEngine/src/assets/user_profile_import.hpp:31:25: error: ‘uint8_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
   31 |   using ScanCode = std::uint8_t;
      |                         ^~~~~~~
      |                         wint_t
RigelEngine/src/assets/user_profile_import.hpp:33:3: error: ‘ScanCode’ no nombra a un tipo
   33 |   ScanCode mUpKeybinding;
      |   ^~~~~~~~
RigelEngine/src/assets/user_profile_import.hpp:34:3: error: ‘ScanCode’ no nombra a un tipo
   34 |   ScanCode mDownKeybinding;
      |   ^~~~~~~~
RigelEngine/src/assets/user_profile_import.hpp:35:3: error: ‘ScanCode’ no nombra a un tipo
   35 |   ScanCode mLeftKeybinding;
      |   ^~~~~~~~
RigelEngine/src/assets/user_profile_import.hpp:36:3: error: ‘ScanCode’ no nombra a un tipo
   36 |   ScanCode mRightKeybinding;
      |   ^~~~~~~~
RigelEngine/src/assets/user_profile_import.hpp:37:3: error: ‘ScanCode’ no nombra a un tipo
   37 |   ScanCode mJumpKeybinding;
      |   ^~~~~~~~
RigelEngine/src/assets/user_profile_import.hpp:38:3: error: ‘ScanCode’ no nombra a un tipo
   38 |   ScanCode mFireKeybinding;
      |   ^~~~~~~~
RigelEngine/src/assets/user_profile_import.hpp:47:8: error: ‘uint8_t’ in namespace ‘std’ does not name a type; did you mean ‘wint_t’?
   47 |   std::uint8_t mGameSpeedIndex;
      |        ^~~~~~~
      |        wint_t
[ 24%] Building CXX object src/CMakeFiles/rigel_core.dir/audio/sound_system.cpp.o
RigelEngine/src/assets/user_profile_import.cpp: En la función lambda:
RigelEngine/src/assets/user_profile_import.cpp:194:37: error: ‘ScanCode’ en ‘struct rigel::assets::GameOptions’ no nombra un tipo
  194 |     return static_cast<GameOptions::ScanCode>(
      |                                     ^~~~~~~~
RigelEngine/src/assets/user_profile_import.cpp: In function ‘std::optional<rigel::assets::GameOptions> rigel::assets::loadOptions(const std::string&)’:
RigelEngine/src/assets/user_profile_import.cpp:206:12: error: ‘struct rigel::assets::GameOptions’ has no member named ‘mUpKeybinding’
  206 |     result.mUpKeybinding = asScanCode(reader.readU16());
      |            ^~~~~~~~~~~~~
RigelEngine/src/assets/user_profile_import.cpp:207:12: error: ‘struct rigel::assets::GameOptions’ has no member named ‘mDownKeybinding’
  207 |     result.mDownKeybinding = asScanCode(reader.readU16());
      |            ^~~~~~~~~~~~~~~
RigelEngine/src/assets/user_profile_import.cpp:208:12: error: ‘struct rigel::assets::GameOptions’ has no member named ‘mLeftKeybinding’
  208 |     result.mLeftKeybinding = asScanCode(reader.readU16());
      |            ^~~~~~~~~~~~~~~
RigelEngine/src/assets/user_profile_import.cpp:209:12: error: ‘struct rigel::assets::GameOptions’ has no member named ‘mRightKeybinding’
  209 |     result.mRightKeybinding = asScanCode(reader.readU16());
      |            ^~~~~~~~~~~~~~~~
RigelEngine/src/assets/user_profile_import.cpp:210:12: error: ‘struct rigel::assets::GameOptions’ has no member named ‘mJumpKeybinding’
  210 |     result.mJumpKeybinding = asScanCode(reader.readU16());
      |            ^~~~~~~~~~~~~~~
RigelEngine/src/assets/user_profile_import.cpp:211:12: error: ‘struct rigel::assets::GameOptions’ has no member named ‘mFireKeybinding’
  211 |     result.mFireKeybinding = asScanCode(reader.readU16());
      |            ^~~~~~~~~~~~~~~
RigelEngine/src/assets/user_profile_import.cpp:223:12: error: ‘struct rigel::assets::GameOptions’ has no member named ‘mGameSpeedIndex’
  223 |     result.mGameSpeedIndex =
      |            ^~~~~~~~~~~~~~~
[ 24%] Building CXX object src/CMakeFiles/rigel_core.dir/base/array_view.cpp.o
[ 25%] Building CXX object src/CMakeFiles/rigel_core.dir/base/image.cpp.o
make[2]: *** [src/CMakeFiles/rigel_core.dir/build.make:244: src/CMakeFiles/rigel_core.dir/assets/user_profile_import.cpp.o] Error 1
make[2]: *** Se espera a que terminen otras tareas....
make[1]: *** [CMakeFiles/Makefile2:506: src/CMakeFiles/rigel_core.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by lethal-guitar** [comment]
@orderorder thanks for the report. Try adding a line with `#include <cstdint>` after this line:
https://github.com/lethal-guitar/RigelEngine/blob/417e0577129001f7511fa9641a31805a55fbb6fe/src/assets/user_profile_import.hpp#L24

Does that fix the error?


Also, which compiler are you using?

**Comment by orderorder** [comment]
It Works. I am using the gcc 13.2.1-3 compiler on my linux Endeavor OS. 

What plans do you have for this engine in the future? 
Are you involved in other engines? 

Thank you

**Comment by lethal-guitar** [comment]
Great! I will also add this fix to the code as soon as I have time.

Currently, I don't have any concrete plans for this project - I've been working on it for more than 5 years, it's fairly complete w.r.t my original vision, and I have other projects and ideas I'd like to focus on. I'm still aiming to do some basic maintenance as needed, but I won't do any new features or larger changes for the foreseeable future.
