### ISSUE TITLE
compilation error in linux (error: ‘sort’ is not a member of ‘std’)

### ISSUE THREAD

**Issue by orderorder** [lethal-guitar/RigelEngine#923]
imfilebrowser.cpp:420:10: error: ‘sort’ is not a member of ‘std’

gcc versión 14.1.1 20240507

I was able to find the solution adding on the file /3rd_party/imgui-filebrowser/imfilebrowser.cpp

`#include <algorithm>`

**Comment by lethal-guitar** [comment]
Thanks for letting me know, I'll look into it

**Comment by lethal-guitar** [comment]
This should be fixed now on the latest `master` branch. Feel free to reopen if it's still a problem.
